blank_issues_enabled: false
contact_links:
  - name: Just have a question?
    url: https://github.com/mtdvlpr-org/bible-time/discussions
    about: Please ask and answer questions in the discussions section.
